version: '3.8'  
services:  
  db:
    image: mariadb
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  app:
    build:
      context: .
    command: uvicorn my-api.main:app --reload
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  mysql:
  mysql_config: