version: '3.6'  
services:  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn my-api.main:app --reload
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306